### PR TITLE
Update Program.cs

### PR DESCRIPTION
**Pull request by amirnizamiev**

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello Amir.

In the 1st task a lot of exceed information. Remove it.
It wrong formula. Order have sence.
double an = S / 2 * n - a0;

You have 2 attempts left.

**Comment by amirnizamiev** [comment]
> Hello Amir.
> 
> In the 1st task a lot of exceed information. Remove it. It wrong formula. Order have sence. double an = S / 2 * n - a0;
> 
> You have 2 attempts left.

What exactly is superfluous? I cant understand

**Comment by NemirovichMark** [comment]
* 1. Find your BMI - body mass index
*
1 formula is enough. Everything other - superfluous.

**Comment by NemirovichMark** [comment]
Already accepted.

**Pull request closed without merging**
