### PR TITLE
1st Lab

### PR DESCRIPTION
**Pull request by Georgii11111**
Hello Mark,

I did everything!

Could you give me pass to 1st lab work, please?

1 task: https://pastebin.com/7B9AQQcT

2 task: https://pastebin.com/Lq198b4P

3 task: https://pastebin.com/xF2zqRNC

### CODE REVIEW

**Comment by NemirovichMark** [comment]
Hello.

It is wonderful that you know about pastebin. But I asked to use Github, because here your progress will be clear and time-defined.

So, please, add your solutions to your repository.
Also in the 3rd task an error DivisionByZero occurred. And keep in your mind that n shoudn't be negative!

You have 2 attempts left.

**Comment by Georgii11111** [comment]
I upload the file

**Comment by NemirovichMark** [comment]
Reload

**Comment by NemirovichMark** [comment]
All done well.

You can make fork of this repository:
https://github.com/NemirovichMark/1st_Lab
And find task here:
https://lms.misis.ru/courses/18063/files?preview=3472463
I will create a branch for your answer soon.

**Pull request merged**
