### PR TITLE
1st, 2nd, 3rd

### PR DESCRIPTION
**Pull request by KovalevNikolay710**
I've done everything, probably.

### CODE REVIEW

**Comment by KovalevNikolay710** [comment]
Now I've definitely done it

**Comment by NemirovichMark** [comment]
Nikolay

I don't see any changes.
Where do you upload them?

Last change in your repository:
https://github.com/KovalevNikolay710/1st_Lesson
were 3h ago since moment of this message. And you 2h ago wrote "Now I've definitely done it".

It is good, that you have done it. But please, change it in your repository (upload or direct ctrl+v) and after that push the request to your branch in my repository.

If you don't understand how it should be done, look at presentations once more, please.

**Comment by KovalevNikolay710** [comment]
i uploud them it in Program.cs

**Comment by KovalevNikolay710** [comment]
I upload it in Program.cs

**Pull request closed without merging**
